export enum AuthActionType {
    USER_LOGGED_IN = 'USER_LOGGED_IN',
    USER_LOGGED_OUT = 'USER_LOGGED_OUT',
    USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
    SET_APP_CONTEXT = 'SET_APP_CONTEXT'
}

export enum ReportActionType {
    GET_STATIC_DATA = 'GET_STATIC_DATA',
    GET_STATIC_DATA_FAILED = 'GET_STATIC_DATA_FAILED',
    USER_REGISTER = 'USER_REGISTER',
    USER_REGISTER_FAILED = 'USER_REGISTER_FAILED',
    SAVE_APPLICATION_FORM = 'SAVE_APPLICATION_FORM',
    SAVE_APPLICATION_FORM_FAILED = 'SAVE_APPLICATION_FORM_FAILED',
    SET_APPLICATION_ID = 'SET_APPLICATION_ID',
    SET_USER_DETAILS = 'SET_USER_DETAILS',
    SET_TAB_NUMBER = 'SET_TAB_NUMBER'
}